name: Production Release

on:
  # 1) Allows to run the workflow manually from the GitHub UI
  workflow_dispatch:
  
  # 2) Runs automatically every Thursday at 9am PST
  # NOTE: GitHub Actions schedule uses UTC, so 9am PST corresponds to 17:00 UTC (PST is UTC-8).
  schedule:
    - cron: "0 17 * * 2"

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  set-date:
    name: Set Date
    runs-on: ubuntu-latest
    outputs:
      DATE_TAG: ${{ steps.date_tag.outputs.DATE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Date tag
        id: date_tag
        run: |
          echo "DATE_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
  
  retag-prod:
    needs: ["set-date"]
    uses: ./.github/workflows/releaseTemplate.yaml
    with:
      TARGET_TAG: "staging"
      TAGS: "prod-${{ needs.set-date.outputs.DATE_TAG }} prod"
