name: Release Workflow

on:
  workflow_call:
    inputs:
      TARGET_TAG:
        description: "Which docker tag to retag from"
        required: true
        type: string

      TAGS:
        description: "Which docker tag(s) to retag to"
        required: true
        type: string

jobs:
  paracord:
    uses: ./.github/workflows/retagDockerTargets.yaml
    with:
      TARGET_TAG: ${{ inputs.TARGET_TAG }}
      TARGETS: "paracord"
      TAGS: ${{ inputs.TAGS }}
      
  paranet:
    uses: ./.github/workflows/retagDockerTargets.yaml
    with:
      TARGET_TAG: ${{ inputs.TARGET_TAG }}
      TARGETS: "paranet-broker paranet-service paranet-broker-sim"
      TAGS: ${{ inputs.TAGS }}
      REPO: "paranet-broker/"
      
  paraflow:
    uses: ./.github/workflows/retagDockerTargets.yaml
    with:
      TARGET_TAG: ${{ inputs.TARGET_TAG }}
      TARGETS: "paraflow paraflow-sim debugger"
      TAGS: ${{ inputs.TAGS }}
      REPO: "paraflow/"




