name: Slack Notification

on:
  # Uncomment the following lines to trigger the workflow on push to a specific branch (for testing or feature-specific deployments)
  # push:
  #   branches:
  #     - feature/DEV-313

  # Trigger the workflow when the "Staging Release" or "Production Release" workflows complete
  workflow_run:
    workflows: ["Staging Release", "Production Release"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  slack-notification:
    name: Notify Slack
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Determine Release Type
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "RELEASE_TYPE=Feature-test" >> $GITHUB_ENV
          elif [[ "${{ github.event.workflow_run.name }}" == "Staging Release" ]]; then
            echo "RELEASE_TYPE=Staging" >> $GITHUB_ENV
          else
            echo "RELEASE_TYPE=Production" >> $GITHUB_ENV
          fi

      - name: Set Date and Version
        id: set_version
        run: |
          DATE_TAG=$(date +'%Y.%m.%d')
          if [[ "$RELEASE_TYPE" == "Staging" ]]; then
            VERSION="staging-${DATE_TAG}"
          elif [[ "$RELEASE_TYPE" == "Production" ]]; then
            VERSION="prod-${DATE_TAG}"
          else
            VERSION="test-${DATE_TAG}"
          fi
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get Release Versions
        id: get_versions
        run: |
          PARANET_VERSION=$(curl -sL -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/otonoma/paranet-broker/releases/latest" | jq -r .tag_name)
          PARAFLOW_VERSION=$(curl -sL -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/otonoma/paraflow/releases/latest" | jq -r .tag_name)
          PARACORD_VERSION=$(curl -sL -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/otonoma/paracord/releases/latest" | jq -r .tag_name)
          echo "PARANET_VERSION=$PARANET_VERSION" >> $GITHUB_ENV
          echo "PARAFLOW_VERSION=$PARAFLOW_VERSION" >> $GITHUB_ENV
          echo "PARACORD_VERSION=$PARACORD_VERSION" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "🚀 New ${{ env.RELEASE_TYPE }} Release! 🚀"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    🚀 *New Release!* 🚀

                    🏷️ *Environment:* ${{ env.RELEASE_TYPE == 'Production' && 'PROD' || env.RELEASE_TYPE == 'Staging' && 'STAGING' || 'FEATURE TEST' }}
                    📅 *Date:* ${{ env.DATE_TAG }}
                    📦 *Version:* ${{ env.VERSION }}
                    
                    *Paranet: ${{ env.PARANET_VERSION }}*
                    :file_folder: *Published Artifacts:*
                    ```
                    • ghcr.io/otonoma/paranet-broker/paranet-broker:${{ env.VERSION }}
                    • ghcr.io/otonoma/paranet-broker/paranet-service:${{ env.VERSION }}
                    • ghcr.io/otonoma/paranet-broker/paranet-broker-sim:${{ env.VERSION }}
                    ```
                    *Release Details:*
                    • https://github.com/otonoma/paranet-broker/releases/tag/${{ env.PARANET_VERSION }}
                    
                    *Paraflow: ${{ env.PARAFLOW_VERSION }}*
                    :file_folder: *Published Artifacts:*
                    ```
                    • ghcr.io/otonoma/paraflow/paraflow:${{ env.VERSION }}
                    • ghcr.io/otonoma/paraflow/paraflow-sim:${{ env.VERSION }}
                    ```
                    *Release Details:*
                    • https://github.com/otonoma/paraflow/releases/tag/${{ env.PARAFLOW_VERSION }}

                    *Paracord: ${{ env.PARACORD_VERSION }}*
                    :file_folder: *Published Artifacts:*
                    ```
                    • ghcr.io/otonoma/paracord:${{ env.VERSION }}
                    ```
                    *Release Details:*
                    • https://github.com/otonoma/paracord/releases/tag/${{ env.PARACORD_VERSION }}
