name: Slack Notification

on:
  push:
    branches:
      - feature/DEV-313
  workflow_run:
    workflows: ["Staging Release"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  slack-notification:
    name: Notify Slack
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Set Placeholder Images
        id: set_images
        run: |
          echo "IMAGES<<EOF" >> $GITHUB_ENV
          echo "ghcr.io/grokit-data/app1:latest" >> $GITHUB_ENV
          echo "ghcr.io/grokit-data/app2:latest" >> $GITHUB_ENV
          echo "ghcr.io/grokit-data/app3:latest" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            blocks:
                text:
                  type: "mrkdwn"
                  text: |
                    :rocket: *New Release Pushed!* :rocket:
                        
                    :calendar: *Date:* ${{ github.event.head_commit.timestamp || github.event.workflow_run.created_at }}
                    :package: *Commit:* ${{ github.event.head_commit.id || github.event.workflow_run.head_sha || 'unknown' }}
                    :file_folder: *Published Artifacts:*
                    ```
                    ${{ env.IMAGES }}
                    ```
                    :label: *Environment:* ${{ github.ref == 'refs/heads/main' && 'PROD' || 'STG' }}
