name: Staging Release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  set-date:
    name: Set Date
    runs-on: ubuntu-latest
    outputs:
      DATE_TAG: ${{ steps.date_tag.outputs.DATE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Date tag
        id: date_tag
        run: |
          echo "DATE_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

  retag-staging:
    uses: ./.github/workflows/releaseTemplate.yaml@main
    with:
      TARGET_TAG: "latest"
      TAGS: "staging-${{ needs.set-date.outputs.DATE_TAG }} staging"
    # secrets: inherit
