name: Staging Release
run-name: Staging Release

on:
  workflow_dispatch:
    inputs: {}

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  set-date:
    name: Set Date
    runs-on: ubuntu-latest
    outputs:
      DATE_TAG: ${{ steps.date_tag.outputs.DATE_TAG }}
    steps:
      - name: Date tag
        id: date_tag
        run: |
          echo "DATE_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "DATE_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          
  retag-paracord:
    name: Retag Paracord
    needs: [set-date]
    uses: grokit-data/common-workflows/.github/workflows/retagDockerTargets.yml@main
    with:
      TARGET_TAG: latest
      TARGETS: "paracord"
      TAGS: "staging"
      
  retag-paranet:
    name: Retag
    needs: [set-date]
    uses: grokit-data/common-workflows/.github/workflows/retagDockerTargets.yml@main
    with:
      TARGET_TAG: latest
      TARGETS: "paranet-broker paranet-service paranet-broker-sim"
      TAGS: "staging"
      REPO: "paranet-broker/"

  retag-paraflow:
    name: Retag Paraflow
    needs: [set-date]
    uses: grokit-data/common-workflows/.github/workflows/retagDockerTargets.yml@main
    with:
      TARGET_TAG: latest
      TARGETS: "paraflow paraflow-sim debugger"
      TAGS: "staging"
      REPO: "paraflow/"
